[package]
name = "yew-tube-converter"
version = "0.1.0"
edition = "2021"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yew = { version = "0.20", features = ["csr"] }
wasm-bindgen = "0.2"
web-sys = "0.3"


[[bin]]
path = "src/main.rs"
name = "yew_tube_converter"

[lib]
crate-type = ["cdylib", "rlib"]
