[build]
target = "index.html"
dist = "docs"
filehash = false

[output]
dir = "docs"

[[asset]]
dir = "/assets"
url_prefix = "/assets"

[dev]
public_url = "/"

[release]
public_url = "/"
