[build]
public_url = "/"
target = "index.html"

[output]
dir = "dist"

[output.js]
file = "yew-tube-converter.js"
dir = "dist"

[output.wasm]
file = "yew-tube-converter_bg.wasm"
dir = "dist"
